###

GET http://localhost:3000/todos/


###
GET http://localhost:3000/todos/6/

###
GET http://localhost:3000/todos/agenda/?date=2021-13-15

###
POST http://localhost:3000/todos/
Content-Type: application/json

{
    "id":6,
    "todo":"Finalize event",
    "priority":"Low",
    "status":"TO DO",
    "category":"HOME",
    "dueDate":"2021-13-15"
}


###
PUT http://localhost:3000/todos/1/
Content-Type: application json

{
    "status":"DONE"
}

###
DELETE http://localhost:3000/todos/1/
